### ISSUE TITLE
Overloading array behavior 

### ISSUE THREAD

**Issue by datnamer** [plures/libxnd#2]
Can array behavior like slicing be changed/overloaded for user defined subtypes?

**Comment by skrah** [comment]
The current vision for `xnd` is to implement *one* specific *fast* array type that supports variable dimensions, zero copy sub-arrays, missing values and dimensions, nested arra If the type has only fixed dimensions, the array should be compatible with NumPy's ndarray.  If the type has variable dimensions, the bitmaps and "offset" arrays are Arrow compatible.

On top of that we need to support multidimensional slicing and indexing (which to my knowledge Arrow does not).

These are a lot of requirements.  Supporting overloading is IMHO only possible a) if one sacrifices speed and b) uses a completely different approach that would amount to writing a new compiled language.

**Comment by datnamer** [comment]
@sklam @teoliphant will anything like that (compiled abstract overloadable array interface ) be possible in numba? Xnd can then be plugged in.
